### ISSUE TITLE
Feedback op README

### ISSUE THREAD

**Issue by Kitkatisvibing** [Nawallox/look-and-feel-styleguide#4]
Readme is erg algemeen en geeft niet veel informatie over dit project. Er staan categorieën voor kleuren en typografie maar daar staat geen informatie in. Misschien helpt het om wat plaatjes/screenshots toe te voegen voor duidelijkheid

@keremttc @Ravirkt @nadiachaja

**Comment by Nawallox** [comment]
Stella pakt de Readme op

**Comment by misspastelwitch** [comment]
The readme has been updated!
